#!/usr/bin/env python
from flask import Flask


app = Flask(__name__)
app.debug = True


@app.route('/', methods=['GET'])
def the_root():
    return '\\m/'


@app.route('/android/', methods=['GET'])
def gather_android():
    return 'ok'


if __name__ == "__main__":
    app.run()